---

# Whenever this file is modified, we must re-sign it for Drone:
# $ drone sign bluerogue251/DBSubsetter --save

kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    command: ["postgres", "-c", "max_connections=200"]

  - name: sql_server
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      SA_PASSWORD: "MsSqlServerLocal1"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    command: ["/opt/mssql/bin/sqlservr"]

  - name: mysql_origin
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: code_style_check
    image: bluerogue251/db-subsetter-ci:7
    commands:
      - sbt scalafmtCheck

  - name: compile
    image: bluerogue251/db-subsetter-ci:7
    commands:
      - sbt compile test:compile

  - name: unit_tests
    image: bluerogue251/db-subsetter-ci:7
    commands:
      - sbt "testOnly unit.* trw.dbsubsetter.*"

  - name: integration_tests
    image: bluerogue251/db-subsetter-ci:7
    commands:
      - sbt "testOnly integration.*"

  - name: end_to_end_tests
    image: bluerogue251/db-subsetter-ci:7
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
      DB_SUBSETTER_SQL_SERVER_HOST: sql_server
      DB_SUBSETTER_MYSQL_ORIGIN_HOST: mysql_origin
      DB_SUBSETTER_MYSQL_TARGET_HOST: mysql_target
      DB_SUBSETTER_MYSQL_ORIGIN_PORT: 3306
      DB_SUBSETTER_MYSQL_TARGET_PORT: 3306
    commands:
      - sbt "testOnly e2e.*"

---
kind: signature
hmac: c738f6ba607e3b4763d6b2e2c5f35fce5510c201b9310b78fc0bce20a1c5ed21

...
