---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    command: ["postgres", "-c", "max_connections=200"]

  - name: sql_server
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      SA_PASSWORD: "MsSqlServerLocal1"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    command: ["/opt/mssql/bin/sqlservr"]

  - name: mysql_origin
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_single_threaded
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_akka_streams
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
#  - name: test
#    image: bluerogue251/db-subsetter-ci:5
#    environment:
#      DB_SUBSETTER_POSTGRES_HOST: postgres
#      DB_SUBSETTER_SQL_SERVER_HOST: sql_server
#      DB_SUBSETTER_MYSQL_ORIGIN_HOST: mysql_origin
#      DB_SUBSETTER_MYSQL_TARGET_SINGLE_THREADED_HOST: mysql_target_single_threaded
#      DB_SUBSETTER_MYSQL_TARGET_AKKA_STREAMS_HOST: mysql_target_akka_streams
#      DB_SUBSETTER_MYSQL_ORIGIN_PORT: 3306
#      DB_SUBSETTER_MYSQL_TARGET_SINGLE_THREADED_PORT: 3306
#      DB_SUBSETTER_MYSQL_TARGET_AKKA_STREAMS_PORT: 3306
#    commands:
#      - sbt "testOnly unit.* integration.* e2e.*"
  - name: build_jar
    image: bluerogue251/db-subsetter-ci:5
    commands:
      - sbt 'set test in assembly := {}' 'set version := "${DRONE_COMMIT_SHA}"' assembly
  - name: upload_jar
    image: bluerogue251/db-subsetter-ci:5
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - echo "foo"
      - echo $AWS_ACCESS_KEY_ID
      - aws s3 cp /drone/src/target/scala-2.12/DBSubsetter-assembly-${DRONE_COMMIT_SHA}.jar s3://db-subsetter/load-test/jars/
  - name: load_test
    image: bluerogue251/db-subsetter-ci:5
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
    commands:
      - sbt "testOnly load.schooldb.SchoolDbTestPostgreSQL"
---
kind: signature
hmac: cd6fb0a6cffe61b8bfa9a592970fd7c41d1df8f5e0bf8b7c8d0174c8de68fde2

...
