---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: bluerogue251/db-subsetter-sbt:4
    commands:
      - sbt compile
      - sbt testCompile
      - sbt "testOnly unit.*"
      - sbt "testOnly integration.*"
---
kind: signature
hmac: 6174e34ed04a194b12466180b5d61a05859d36ffc1aac9c1663533d070767d4b

...
