---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    command: ["postgres", "-c", "max_connections=200"]

  - name: mysql_origin
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_single_threaded
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_akka_streams
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: test
    image: bluerogue251/db-subsetter-ci:2
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
      DB_SUBSETTER_MYSQL_HOST: mysql
      DB_SUBSETTER_MYSQL_ORIGIN_PORT: 3306
      DB_SUBSETTER_MYSQL_TARGET_SINGLE_THREADED_PORT: 3306
      DB_SUBSETTER_MYSQL_TARGET_AKKA_STREAMS_PORT: 3306
    commands:
      - sbt "testOnly unit.* integration.* e2e.*PostgreSQL e2e.*MySql e2e.pgdatatypes.* e2e.mysqldatatypes.*"
---
kind: signature
hmac: 31a1f0a498ea386008aee70e07f54bdc248841129c48d1140e8c9c5c5667730d

...
