---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: bluerogue251/db-subsetter-sbt:4
    commands:
      - sbt compile
      - sbt test:compile
      - sbt "testOnly unit.*"
      - sbt "testOnly integration.*"
---
kind: signature
hmac: f471211e4d107b5ad80df662bbec792d1f6144ae9b060c80c3ab773bae227adb

...
