---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3

steps:
  - name: test
    image: bluerogue251/db-subsetter-ci:1
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
    commands:
      - sbt "testOnly unit.* integration.* e2e.*PostgreSQL e2e.pgdatatypes.PostgreSQLDataTypesTest"
---
kind: signature
hmac: 15be51b0a8ee0017155704e3b6a5deb6529ee3120d44872dc053d64fd43009d0

...
