---

# Whenever this file is modified, we must re-sign it for Drone:
# $ drone sign bluerogue251/DBSubsetter --save

kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    command: ["postgres", "-c", "max_connections=200"]

  - name: sql_server
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      SA_PASSWORD: "MsSqlServerLocal1"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    command: ["/opt/mssql/bin/sqlservr"]

  - name: mysql_origin
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_single_threaded
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  - name: mysql_target_akka_streams
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

steps:
  - name: code_style_check
    image: bluerogue251/db-subsetter-ci:6
    commands:
      - sbt scalafmtCheckAll

  - name: compile
    image: bluerogue251/db-subsetter-ci:6
    commands:
      - sbt compile test:compile

  - name: unit_tests
    image: bluerogue251/db-subsetter-ci:6
    commands:
      - sbt "testOnly unit.*"

  - name: integration_tests
    image: bluerogue251/db-subsetter-ci:6
    commands:
      - sbt "testOnly integration.*"

  - name: end_to_end_tests
    image: bluerogue251/db-subsetter-ci:6
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
      DB_SUBSETTER_SQL_SERVER_HOST: sql_server
      DB_SUBSETTER_MYSQL_ORIGIN_HOST: mysql_origin
      DB_SUBSETTER_MYSQL_TARGET_SINGLE_THREADED_HOST: mysql_target_single_threaded
      DB_SUBSETTER_MYSQL_TARGET_AKKA_STREAMS_HOST: mysql_target_akka_streams
      DB_SUBSETTER_MYSQL_ORIGIN_PORT: 3306
      DB_SUBSETTER_MYSQL_TARGET_SINGLE_THREADED_PORT: 3306
      DB_SUBSETTER_MYSQL_TARGET_AKKA_STREAMS_PORT: 3306
    commands:
      - sbt "testOnly e2e.*"

  - name: load_test
    image: bluerogue251/db-subsetter-ci:6
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
    commands:
      - sbt "testOnly load.schooldb.SchoolDbTestPostgreSQL"

---
kind: signature
hmac: 6ebd6b7ed6308914b200559fd9f835cf7e1036d0c00f83f6d4e2af3e731bd0b7

...
