---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    ports:
      - "5432:5432"

steps:
  - name: test
    image: bluerogue251/db-subsetter-sbt:4
    commands:
      - sbt "testOnly unit.* integration.* e2e.pgdatatypes.PostgreSQLDataTypesTest"
---
kind: signature
hmac: b8b107f924972368623a17b5162c627787f193f2833e2e443874728221ce3784

...
