---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3
    command: ["postgres", "-c", "max_connections=200"]

steps:
  - name: test
    image: bluerogue251/db-subsetter-ci:2
    environment:
      DB_SUBSETTER_POSTGRES_HOST: postgres
      DB_SUBSETTER_MYSQL_HOST: mysql
    commands:
      - sbt "testOnly unit.* integration.* e2e.*PostgreSQL e2e.pgdatatypes.PostgreSQLDataTypesTest"
---
kind: signature
hmac: 9ee06d4253e851372bfca17919a2a1e171073486190f7ad38fed093b9e6a6b90

...
