---
kind: pipeline
type: docker
name: default

services:
  - name: postgres
    image: postgres:9.6.3

steps:
  - name: test
    image: bluerogue251/db-subsetter-sbt:4
    commands:
      - sbt "testOnly unit.* integration.* e2e.pgdatatypes.PostgreSQLDataTypesTest"
---
kind: signature
hmac: e2787ce46f420e4945abb59d446ee7ca5bb938609bc2dcc8d176091c8c8b5612

...
