version: "3"

services:
  postgres:
    image: postgres:9.6.3
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"

  mysql_origin:
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"

  mysql_target_single_threaded:
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3307:3306"

  mysql_target_akka_streams:
    image: mysql:8.0.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3308:3306"
