{
 "title": "DBSubsetter Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Notable Event Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(OriginDbRowsFetchedPerStatement_sum[1s])",
     "legendFormat": "Rows Fetched from Origin DB Per Second"
    },
    {
     "expr": "rate(TargetDbRowsInsertedPerStatement_sum[1s])",
     "legendFormat": "Rows Inserted into Target DB Per Second"
    },
    {
     "expr": "rate(DuplicateOriginDbRowsDiscarded[1s])",
     "legendFormat": "Duplicate Origin DB Rows Discarded Per Second"
    },
    {
     "expr": "rate(DuplicateFkTasksDiscarded[1s])",
     "legendFormat": "Duplicate ForeignKeyTasks Discarded Per Second"
    }
   ]
  },
  {
   "title": "DB Row Totals",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "OriginDbRowsFetchedPerStatement_sum - DuplicateOriginDbRowsDiscarded",
     "legendFormat": "Total Unique Rows Fetched from Origin DB"
    },
    {
     "expr": "TargetDbRowsInsertedPerStatement_sum",
     "legendFormat": "Total Rows Inserted into Target DB"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "PendingTasks", "legendFormat": "Pending Task Count" }
   ]
  },
  {
   "title": "DB Average Time Spent Per Row",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(OriginDbDurationPerRow_sum[1s]) / rate(OriginDbDurationPerRow_count[1s])",
     "legendFormat": "Origin DB Row Fetched"
    },
    {
     "expr": "rate(TargetDbDurationPerRow_sum[1s]) / rate(TargetDbDurationPerRow_count[1s])",
     "legendFormat": "Target DB Row Inserted"
    }
   ]
  },
  {
   "title": "DB Average Rows Processed Per Statement",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(OriginDbRowsFetchedPerStatement_sum[1s]) / rate(OriginDbRowsFetchedPerStatement_count[1s])",
     "legendFormat": "Origin DB Average Rows Fetched Per Statement"
    },
    {
     "expr": "rate(TargetDbRowsInsertedPerStatement_sum[1s]) / rate(TargetDbRowsInsertedPerStatement_count[1s])",
     "legendFormat": "Target DB Average Rows Inserted Per Statement"
    }
   ]
  },
  {
   "title": "DB Statements Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(OriginDbRowsFetchedPerStatement_count[1s])",
     "legendFormat": "Origin DB"
    },
    {
     "expr": "rate(TargetDbRowsInsertedPerStatement_count[1s])",
     "legendFormat": "Target DB"
    }
   ]
  },
  {
   "title": "Average Time Spent Per Non-DB Operation (1 operation ~= 1 row)",
   "type": "graph",
   "description": "1 operations is only approximately equal to 1 row, as a single row can result in multiple foreign key tasks being written to the FkTask Buffer.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(PrimaryKeyStoreMarkSeen_sum[1s]) / rate(PrimaryKeyStoreMarkSeen_count[1s])",
     "legendFormat": "PkStore MarkSeen"
    },
    {
     "expr": "rate(PrimaryKeyStoreMarkSeenWithChildren_sum[1s]) / rate(PrimaryKeyStoreMarkSeenWithChildren_count[1s])",
     "legendFormat": "PkStore MarkSeenWithChildren"
    },
    {
     "expr": "rate(PrimaryKeyStoreQueryAlreadySeen_sum[1s]) / rate(PrimaryKeyStoreQueryAlreadySeen_count[1s])",
     "legendFormat": "PkStore QueryAlreadySeen"
    },
    {
     "expr": "rate(TaskEnqueueDuration_sum[1s]) / rate(TaskEnqueueDuration_count[1s])",
     "legendFormat": "FkTask Buffer Enqueue"
    },
    {
     "expr": "rate(TaskDequeueDuration_sum[1s]) / rate(TaskDequeueDuration_count[1s])",
     "legendFormat": "FkTask Buffer Dequeue"
    }
   ]
  },
  {
   "title": "Origin DB Query JDBC Result to Scala Object Conversion Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(OriginDbJdbcResultToObjectMapper_sum[1s]) / rate(OriginDbJdbcResultToObjectMapper_count[1s])",
     "legendFormat": "JDBC Result to Scala Object Conversion Average Duration"
    }
   ]
  },
  {
   "title": "Pre-Target Buffer Entries (1 Entry Has Many Rows) (Akka Streams Only)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "PreTargetBufferSize", "legendFormat": "Entries" }
   ]
  },
  {
   "title": "Pre-Target Buffer Rows (1 Entry Has Many Rows) (Akka Streams Only)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "PreTargetBufferRows", "legendFormat": "Rows" }
   ]
  },
  {
   "title": "Percent Time Spent in JVM Garbage Collection (Sliding 30 Second Window)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[30s])",
     "legendFormat": "Total Time ({{gc}})"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Memory Used By Pool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\"PS Eden Space|PS Old Gen|PS Survivor Space\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}